version: '3.1'

services:
  db-1:
    container_name: db-1
    hostname: db-1
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
     - ./sql_setup/cluster.cnf.db-1:/etc/mysql/conf.d/cluster.cnf:ro
     - ./sql_setup/replica.sql.db-1:/docker-entrypoint-initdb.d/replica.sql:ro
    ports:
     - 1001:3306/tcp
  db-2:
    container_name: db-2
    hostname: db-2
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
     - ./sql_setup/cluster.cnf.db-2:/etc/mysql/conf.d/cluster.cnf:ro
     - ./sql_setup/replica.sql.db-2:/docker-entrypoint-initdb.d/replica.sql:ro
    ports:
     - 1002:3306/tcp
